### ISSUE TITLE
Diag Level 2

### ISSUE THREAD

**Issue by PeteRager** [HyperActiveJ/home-assistant-lennox-local-https#1]
I don't believe this command is necessary.   Unless you want the diagnostic data....

Here is what I noticed.  Once this command was sent, the S30 appears to also stream all the diag data to the cloud as I could see it inside the logs of HA integration that uses the cloud interface.  So, it is going to consume a bunch of wifi bandwidth - and also probably really slow down the mobile app - as it will receive all the diag data.

I set it back to zero and that seems to disable it.

I don't think the command is required to get the data we would typically want.

**Comment by PeteRager** [comment]
Now that I have your test_lcc working.  I'm going to see if it's possible to adapt the the Cloud API to work with cloud or local.

**Comment by HyperActiveJ** [comment]
Sounds Great!
I commented out the diagnostic data for now.
Looking forward to having it in your implementation. Let me know if there's something I can do.
